#ifndef _FOMULA_SEEKER_DEFINE_H
#define _FOMULA_SEEKER_DEFINE_H

#include <stdlib.h>

#define MAX_TREE_CHILD_NODE 1024;

typedef enum {
	OPERA_INVALID = 0,
	OPERA_PLUS,
	OPERA_SUBTRACT,
	OPERA_MULTIPLE,
	OPERA_DIVIDE
} seeker_operator;

typedef enum {
	TNODE_TYPE_UNKNOWN = 0,
	TNODE_TYPE_ROOT,
	TNODE_TYPE_NUM,
	TNODE_TYPE_OPERATOR
} tree_node_type;

#endif // _FOMULA_SEEKER_DEFINE_H
